import { useEffect, useMemo, useRef, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { FiArrowLeft, FiCheck, FiDownload, FiFile, FiSearch, FiTrash2, FiUploadCloud, FiX } from "react-icons/fi";
import { pdfTools, toolBySlug } from "./pdfTools.jsx";
import { downloadBlob, getPageThumbnails, imagesToPdf, merge, pdfToJpg, splitToZip, transformPdf } from "./pdfEngine.js";
import "./free-tools.css";

const bytes = (n) => n > 1048576 ? `${(n/1048576).toFixed(1)} MB` : `${Math.ceil(n/1024)} KB`;

export function FreeToolsPage() {
  return <main className="ft-page"><section className="ft-hero"><span>مجاني · خاص · داخل متصفحك</span><h1>Free Tools</h1><p>أدوات عملية تعمل محليًا بدون رفع ملفاتك إلى خدمات خارجية.</p></section><section className="ft-categories"><Link to="/free-tools/pdf-tools"><div className="ft-category-icon"><FiFile /></div><div><small>أول مجموعة متاحة</small><h2>PDF Tools</h2><p>{pdfTools.length} أداة لمعالجة ملفات PDF بالكامل داخل جهازك.</p></div><FiArrowLeft /></Link></section></main>;
}

export function PdfToolsPage() {
  const [q,setQ]=useState(""); const filtered=useMemo(()=>pdfTools.filter(t=>`${t.name} ${t.en} ${t.description}`.toLowerCase().includes(q.toLowerCase())),[q]);
  return <main className="ft-page"><section className="ft-hero pdf"><span>Free Tools / PDF</span><h1>أدوات PDF المجانية</h1><p>معالجة آمنة وسريعة داخل المتصفح؛ ملفاتك لا تغادر جهازك.</p><label className="ft-search"><FiSearch/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث عن أداة..."/></label></section><div className="ft-grid">{filtered.map(t=><Link key={t.id} to={`/free-tools/pdf-tools/${t.slug}`} className="ft-card"><span><t.icon/></span><div><h2>{t.name}</h2><small>{t.en}</small><p>{t.description}</p></div><FiArrowLeft/></Link>)}</div>{!filtered.length&&<div className="ft-empty">لا توجد أداة مطابقة لبحثك.</div>}</main>;
}

function Dropzone({ files, setFiles, images, multiple }) {
  const input=useRef(); const accept=images?"image/jpeg,image/png":"application/pdf";
  const add=(list)=>{const incoming=[...list].filter(f=>images?/image\/(jpeg|png)/.test(f.type):f.type==="application/pdf"||f.name.toLowerCase().endsWith(".pdf"));setFiles(multiple?[...files,...incoming]:incoming.slice(0,1));};
  return <><div className="ft-drop" role="button" tabIndex="0" onKeyDown={e=>{if(e.key==="Enter")input.current.click()}} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();add(e.dataTransfer.files)}} onClick={()=>input.current.click()}><FiUploadCloud/><h2>اسحب الملفات هنا</h2><p>أو اضغط لاختيار {images?"صور JPG / PNG":"ملفات PDF"} من جهازك</p><button type="button">اختيار الملفات</button><input ref={input} hidden type="file" accept={accept} multiple={multiple} onChange={e=>add(e.target.files)}/></div>{files.length>0&&<div className="ft-files">{files.map((f,i)=><div key={`${f.name}-${i}`} draggable={multiple} onDragStart={e=>e.dataTransfer.setData("index",i)} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();const from=Number(e.dataTransfer.getData("index"));if(from===i)return;const next=[...files],item=next.splice(from,1)[0];next.splice(i,0,item);setFiles(next)}}><FiFile/><span><b>{f.name}</b><small>{bytes(f.size)}</small></span><button aria-label="إزالة الملف" onClick={()=>setFiles(files.filter((_,x)=>x!==i))}><FiX/></button></div>)}</div>}</>;
}

function Options({tool,options,setOptions}){
 const set=(key,value)=>setOptions({...options,[key]:value});
 if(["extract","remove","duplicate","rotate","crop"].includes(tool.id)) return <div className="ft-options"><label>الصفحات <input value={options.ranges||""} onChange={e=>set("ranges",e.target.value)} placeholder="مثال: 1-3, 5, 8-10"/></label>{tool.id==="rotate"&&<label>زاوية التدوير <select value={options.angle||90} onChange={e=>set("angle",e.target.value)}><option>90</option><option>180</option><option>270</option></select></label>}{tool.id==="crop"&&<label>الهامش بالنقاط <input type="number" min="0" value={options.margin||20} onChange={e=>set("margin",e.target.value)}/></label>}</div>;
 if(tool.id==="split") return <div className="ft-options"><label className="check"><input type="checkbox" checked={!!options.eachPage} onChange={e=>set("eachPage",e.target.checked)}/> كل صفحة في ملف مستقل</label>{!options.eachPage&&<label>المجموعات (افصل بينها بـ ;) <input value={options.ranges||"1-3;4-6"} onChange={e=>set("ranges",e.target.value)} placeholder="1-3;4-6;7"/></label>}</div>;
 if(tool.id==="watermark") return <div className="ft-options"><label>نص العلامة <input value={options.text||"Elhawy AI"} onChange={e=>set("text",e.target.value)}/></label><label>حجم الخط <input type="number" value={options.fontSize||42} onChange={e=>set("fontSize",e.target.value)}/></label><label>الشفافية <input type="range" min=".1" max=".9" step=".1" value={options.opacity||.3} onChange={e=>set("opacity",e.target.value)}/></label></div>;
 if(tool.id==="page-numbers") return <div className="ft-options"><label>رقم البداية <input type="number" value={options.start||1} onChange={e=>set("start",e.target.value)}/></label><label>الموضع <select value={options.position||"center"} onChange={e=>set("position",e.target.value)}><option value="center">المنتصف</option><option value="right">يمين</option><option value="left">يسار</option></select></label><label>حجم الخط <input type="number" value={options.fontSize||12} onChange={e=>set("fontSize",e.target.value)}/></label></div>;
 if(tool.id==="images-to-pdf") return <div className="ft-options"><label>حجم الصفحة <select value={options.size||"a4"} onChange={e=>set("size",e.target.value)}><option value="a4">A4</option><option value="fit">حسب الصورة</option></select></label><label>الاتجاه <select value={options.orientation||"portrait"} onChange={e=>set("orientation",e.target.value)}><option value="portrait">رأسي</option><option value="landscape">أفقي</option></select></label><label>الهامش <input type="number" min="0" value={options.margin||20} onChange={e=>set("margin",e.target.value)}/></label></div>;
 return null;
}

function Organizer({file,order,setOrder,rotations={},setRotations=()=>{},canRotate=false}){
 const [pages,setPages]=useState([]),[loading,setLoading]=useState(true);
 useEffect(()=>{let live=true;setLoading(true);getPageThumbnails(file).then(x=>{if(live){setPages(x);setOrder(x.map(p=>p.index));}}).finally(()=>setLoading(false));return()=>{live=false}},[file]);
 if(loading)return <div className="ft-loading">جارٍ تجهيز صور الصفحات...</div>;
 return <div className="ft-pages">{order.map((idx,pos)=>{const p=pages.find(x=>x.index===idx);return <div key={`${idx}-${pos}`} draggable onDragStart={e=>e.dataTransfer.setData("pos",pos)} onDragOver={e=>e.preventDefault()} onDrop={e=>{const from=Number(e.dataTransfer.getData("pos")),next=[...order],item=next.splice(from,1)[0];next.splice(pos,0,item);setOrder(next)}}><img style={{transform:`rotate(${rotations[pos]||0}deg)`}} src={p?.url} alt={`صفحة ${idx+1}`}/><b>صفحة {idx+1}</b><button aria-label="حذف الصفحة" onClick={()=>setOrder(order.filter((_,i)=>i!==pos))}><FiTrash2/></button>{canRotate&&<button style={{left:"auto",right:14,background:"#e7fbfa",color:"#078f99"}} aria-label="تدوير الصفحة" onClick={()=>setRotations({...rotations,[pos]:((rotations[pos]||0)+90)%360})}>↻</button>}</div>})}</div>;
}

export function PdfToolPage(){
 const {slug}=useParams(),tool=toolBySlug(slug),[files,setFiles]=useState([]),[options,setOptions]=useState({}),[order,setOrder]=useState([]),[rotations,setRotations]=useState({}),[state,setState]=useState("idle"),[error,setError]=useState(""),[progress,setProgress]=useState(0),[result,setResult]=useState(null);
 useEffect(()=>{if(tool)document.title=`${tool.en} - Free PDF Tool | Elhawy AI`;return()=>{document.title="Elhawy AI"}},[tool]);
 if(!tool)return <main className="ft-page"><div className="ft-empty">الأداة غير موجودة.</div></main>;
 const many=tool.mode==="multi"||tool.mode==="images"; const organize=["organize","reorder"].includes(tool.id);
 const run=async()=>{if(!files.length)return setError("اختر ملفًا أولًا.");setState("processing");setError("");setProgress(8);try{let data,name="result.pdf",type="application/pdf";if(tool.id==="merge")data=await merge(files);else if(tool.id==="images-to-pdf")data=await imagesToPdf(files,options);else if(tool.id==="pdf-to-jpg"){data=await pdfToJpg(files[0],setProgress);name="pdf-images.zip";type="application/zip";}else if(tool.id==="split"){data=await splitToZip(files[0],options.ranges||"",options.eachPage,setProgress);name="split-pdf.zip";type="application/zip";}else data=await transformPdf(files[0],tool.id,{...options,order,rotations});setProgress(100);setResult({data,name,type});setState("done");}catch(e){setError(e.message||"تعذر معالجة الملف.");setState("idle");}};
 const reset=()=>{setFiles([]);setOptions({});setOrder([]);setRotations({});setResult(null);setState("idle");setProgress(0);setError("");};
 return <main className="ft-page ft-tool"><Link className="ft-back" to="/free-tools/pdf-tools"><FiArrowLeft/> كل أدوات PDF</Link><header><span><tool.icon/></span><div><small>{tool.en}</small><h1>{tool.name}</h1><p>{tool.description} تتم المعالجة على جهازك ولا يتم رفع الملف.</p></div></header>{state==="done"?<section className="ft-result"><span><FiCheck/></span><h2>الملف جاهز للتحميل</h2><p>اكتملت العملية بنجاح ولم يتم إرسال ملفك لأي خادم.</p><button onClick={()=>downloadBlob(result.data,result.name,result.type)}><FiDownload/> تحميل النتيجة</button><button className="secondary" onClick={reset}>بدء عملية جديدة</button></section>:<section className="ft-workspace"><Dropzone files={files} setFiles={setFiles} images={tool.mode==="images"} multiple={many}/>{files[0]&&organize&&<Organizer file={files[0]} order={order} setOrder={setOrder}/>}<Options tool={tool} options={options} setOptions={setOptions}/>{error&&<div className="ft-error" role="alert">{error}</div>}{state==="processing"?<div className="ft-progress"><div style={{width:`${progress}%`}}/><span>جارٍ المعالجة... {progress}%</span></div>:<button className="ft-run" disabled={!files.length||(organize&&!order.length)} onClick={run}>تنفيذ {tool.name}</button>}</section>}<aside className="ft-privacy"><b>خصوصية كاملة</b><p>كل العمليات تتم داخل متصفحك. لا نرفع ملفاتك ولا نخزنها.</p></aside></main>;
}
