import {FiArrowDown,FiCheck,FiCode,FiCpu,FiEye,FiLock,FiMic,FiMonitor,FiPackage,FiShield,FiSmartphone,FiTool,FiZap} from 'react-icons/fi';

const shared={ar:{tag:'مشروع ذكاء اصطناعي قيد التطوير',title:'جارفيس — وكيلك الذكي لكل شيء',lead:'مساعد متعدد الوسائط يفهم ما تريد، يختار الأداة المناسبة، وينفّذ المهمة على الكمبيوتر والأجهزة من خلال بوابات أمان وموافقة واضحة.',start:'كيف يعمل جارفيس؟',capability:'منظومة قدرات متكاملة',capabilitySub:'ستة محاور تجمع 23 وحدة فعلية داخل تجربة واحدة. افتح أي محور لرؤية التفاصيل.',open:'عرض التفاصيل',safety:'التحكم في يدك دائمًا',safetyText:'العمليات الحساسة لا تُنفّذ خلسة. يمكن ضبط صلاحيات مستقلة للملفات وPowerShell والتحكم بالكمبيوتر والويب والبريد والطباعة والتطوير الذاتي.',status:'حالة المشروع',statusText:'نظام فعلي قيد التطوير والاختبار المستمر. بعض التكاملات تعتمد على الجهاز والشبكة ومفاتيح الخدمات ومواصفات الكمبيوتر.'},en:{tag:'AI project in active development',title:'JARVIS — your agent for everything',lead:'A multimodal assistant that understands intent, selects the right tools, and acts across your computer and devices through explicit approval and security gates.',start:'How JARVIS works',capability:'One connected capability system',capabilitySub:'Six pillars bring 23 working modules into one experience. Open any pillar for details.',open:'View details',safety:'You stay in control',safetyText:'Sensitive operations are never hidden. Files, PowerShell, computer and web control, email, printing and self-modification can each require explicit approval.',status:'Project status',statusText:'A real system under continuous development and testing. Some integrations depend on hardware, network access, service keys or computer specifications.'}};

const flows={ar:[['استقبال الطلب','نص، صوت، صورة، كاميرا، ملف، هاتف، نظارة أو WhatsApp',FiMic],['الفهم والتخطيط','يحلل الهدف ويقسّمه إلى خطوات ويختار النموذج والأداة المناسبة',FiCpu],['الموافقة الآمنة','يطلب إذنك قبل الملفات وPowerShell والتحكم والإرسال والطباعة',FiShield],['التنفيذ والنتيجة','رد، ملف، صورة، نموذج 3D، مشروع، إشعار أو تحكم فعلي',FiZap]],en:[['Capture','Text, voice, image, camera, file, phone, glasses or WhatsApp',FiMic],['Understand & plan','Analyzes the goal, breaks it into steps and selects the right model and tool',FiCpu],['Safe approval','Requests permission before files, PowerShell, control, sending or printing',FiShield],['Execute & deliver','A reply, file, image, 3D model, project, notification or real-world action',FiZap]]};

const groups={ar:[
['المحادثة والرؤية','يتحدث، يسمع ويرى ويتذكر سياق عملك.',FiEye,[['المحادثة الذكية','نص وصوت بالعربية، سجل محادثات، مشاريع ومرفقات، واختيار أجهزة الصوت.'],['الصوت المباشر','استماع منخفض التأخير، مقاطعة الرد، Voicebox محلي وOpenAI Realtime.'],['الرؤية والكاميرا','تحليل كاميرا وصور، YOLO، تتبع وتعرّف محلي على الوجوه.'],['التحكم بالإشارات','تتبع اليد عبر MediaPipe للنقر والسحب والتحكم بالنوافذ.'],['تشغيل الوسائط','تشغيل الصوت والفيديو وYouTube والتحكم الصوتي في المشغل.'],['الذاكرة والمشاريع','سياق منفصل لكل مشروع ومحادثة ومرفقات وذاكرة شخصية.']]],
['الكمبيوتر والويب','ينفّذ العمل بدل الاكتفاء بشرحه.',FiMonitor,[['التحكم الكامل في Windows','فتح التطبيقات والنوافذ، الرؤية، الماوس، لوحة المفاتيح، الملفات، PowerShell والطباعة مع Watchdog.'],['وكيل الويب','تصفح وبحث ونقر وكتابة وتسلسل خطوات عبر Playwright وChromium.'],['التقويم والتذكيرات','مواعيد دائمة وتنبيهات للكمبيوتر والهاتف وأوامر صوتية.'],['البريد الإلكتروني','Gmail وOutlook وقراءة الرسائل وإعداد الرد والمراجعة قبل الإرسال.']]],
['البرمجة والتصنيع','من الفكرة إلى كود أو نموذج قابل للطباعة.',FiCode,[['صناعة المشاريع البرمجية','إنشاء وتعديل مشروعات متعددة الملفات، Code Studio ومعاينة حية وربط العناصر بالكود.'],['CAD والنماذج ثلاثية الأبعاد','نماذج Parametric باستخدام build123d وعرض Three.js وتصدير STL وOBJ وGLB.'],['الطباعة ثلاثية الأبعاد','Moonraker وOctoPrint وPrusaLink وSlicers وتحويل G-code ومراقبة المهمة.'],['إنشاء الصور','توليد صور بأبعاد وNegative Prompt وحفظها داخل المشروع.']]],
['الأجهزة والحياة الذكية','جارفيس معك على الهاتف والنظارة وفي المكان.',FiSmartphone,[['الهاتف','بوابة اقتران آمنة، صوت وصور وGPS وتنبيهات وبريد عبر الشبكة المحلية أو رابط محمي.'],['نظارة JS-03 Pro','صوت ورؤية وصور وموقع وتعرّف على الأشخاص وتنبيهات أثناء الحركة.'],['المنزل الذكي','تحكم Kasa في الإضاءة وBroadLink في أوامر الريموت المسماة والمحفوظة.'],['الأمن والمراقبة','كاميرات وNVR عبر RTSP، بث وتسجيلات وبحث وتتبع وتحليل بصري.']]],
['الأتمتة والتكاملات','يربط خدماتك في سير عمل واحد.',FiPackage,[['التكاملات الخارجية','Composio وWhatsApp وRF Bridge وOpenAI وGemini والبريد وKasa وBroadLink.'],['مركز التداول','Deriv وتحليل السوق والمحفظة والمخاطر والاختبار الخلفي مع مراجعة بشرية صارمة.'],['الذكاء المحلي','Hermes وVoicebox وتوليد صور محلي وتشغيل نماذج حسب قدرات الجهاز.']]],
['الأمن والتطور الذاتي','يتحسن، لكن لا يتجاوز صلاحياتك.',FiLock,[['مركز الأمن','فحص محلي وقواعد Semgrep وعرض الثغرات وفصل أدوات الفحص.'],['التعلم والتطوير الذاتي','دراسة GitHub واقتراح واختبار التحسينات وبناء مهارات Python عبر Ada-SI Forge بعد موافقتك.']]]],
en:[
['Conversation & vision','It speaks, listens, sees and remembers your work context.',FiEye,[['Smart conversation','Arabic text and voice, chat history, projects, attachments and audio-device selection.'],['Realtime voice','Low-latency listening, interruption, local Voicebox and OpenAI Realtime.'],['Vision & camera','Camera and image analysis, YOLO, local face detection and recognition.'],['Gesture control','MediaPipe hand tracking for pointing, clicking and moving windows.'],['Media','Voice-controlled audio, video and YouTube playback.'],['Memory & projects','Independent context for every project, chat and attachment.']]],
['Computer & web','It performs the work instead of only explaining it.',FiMonitor,[['Windows control','Apps, windows, vision, mouse, keyboard, files, PowerShell and printing with a watchdog.'],['Web agent','Playwright and Chromium browsing, search, clicks, typing and multi-step flows.'],['Calendar & reminders','Persistent appointments and notifications across computer and phone.'],['Email','Gmail and Outlook inbox, drafts, review and confirmed sending.']]],
['Code & fabrication','From an idea to software or a printable object.',FiCode,[['Software projects','Multi-file generation and editing, Code Studio, live preview and element-to-code selection.'],['CAD & 3D','Parametric build123d models, Three.js viewing and STL, OBJ and GLB export.'],['3D printing','Moonraker, OctoPrint, PrusaLink, slicers, G-code and job monitoring.'],['Image generation','Configurable generation with negative prompts and project storage.']]],
['Devices & smart life','JARVIS stays with you across phone, glasses and space.',FiSmartphone,[['Phone','Secure pairing, voice, images, GPS, alerts and email over local or protected remote access.'],['JS-03 Pro glasses','Voice, vision, location, person recognition and on-the-go alerts.'],['Smart home','Kasa lighting and named, stored BroadLink remote commands.'],['Security monitoring','RTSP cameras and NVR live view, playback, search, tracking and visual analysis.']]],
['Automation & integrations','It connects services into one continuous workflow.',FiPackage,[['External integrations','Composio, WhatsApp, RF Bridge, OpenAI, Gemini, email, Kasa and BroadLink.'],['Trading center','Deriv market analysis, portfolio, risk and backtesting with strict human review.'],['Local intelligence','Hermes, Voicebox and local image or language models based on available hardware.']]],
['Security & self-improvement','It can improve without moving beyond your authority.',FiLock,[['Security center','Local scans, Semgrep rules, findings and isolated security tooling.'],['Self-improvement','Studies GitHub projects, proposes and tests changes, and builds Python skills through Ada-SI Forge after approval.']]] ]};

export function JarvisPage({lang}){const c=shared[lang];return <main className="jarvis-page"><section className="jarvis-hero"><div className="jarvis-copy"><span>{c.tag}</span><h1>{c.title}</h1><p>{c.lead}</p><a href="#capabilities">{c.start}<FiArrowDown/></a></div><div className="jarvis-core"><span className="core-ring"/><FiCpu/><b>JARVIS</b><small>PERSONAL AI AGENT</small></div></section><section className="jarvis-flow"><header><span>01</span><h2>{c.start}</h2></header><div>{flows[lang].map(([title,text,Icon],i)=><article key={title}><i>{String(i+1).padStart(2,'0')}</i><Icon/><h3>{title}</h3><p>{text}</p></article>)}</div></section><section className="jarvis-capabilities" id="capabilities"><header><span>02</span><h2>{c.capability}</h2><p>{c.capabilitySub}</p></header><div className="capability-grid">{groups[lang].map(([title,text,Icon,items],index)=><details key={title} open={index===0}><summary><span className="capability-icon"><Icon/></span><span><small>{String(index+1).padStart(2,'0')}</small><h3>{title}</h3><p>{text}</p></span><b>{c.open}</b></summary><div className="capability-details">{items.map(([name,description])=><article key={name}><FiCheck/><div><h4>{name}</h4><p>{description}</p></div></article>)}</div></details>)}</div></section><section className="jarvis-trust"><article><FiShield/><div><small>SECURITY BY DESIGN</small><h2>{c.safety}</h2><p>{c.safetyText}</p></div></article><article><FiTool/><div><small>BUILD STATUS</small><h2>{c.status}</h2><p>{c.statusText}</p></div></article></section></main>}
