import {useEffect,useMemo,useState} from'react';
import {Link,useParams} from'react-router-dom';
import {FiArrowLeft,FiBookOpen,FiDownload,FiExternalLink,FiFile,FiFolder,FiLoader,FiSearch} from'react-icons/fi';
import {supabase,supabaseReady} from'./supabase.js';

function useLibrary(){
 const[categories,setCategories]=useState([]),[items,setItems]=useState([]),[loading,setLoading]=useState(true),[error,setError]=useState('');
 useEffect(()=>{if(!supabaseReady){setLoading(false);setError('المكتبة قيد التجهيز');return}Promise.all([
  supabase.from('library_categories').select('*').order('sort_order').order('name'),
  supabase.from('library_items').select('*').eq('published',true).order('created_at',{ascending:false})
 ]).then(([c,i])=>{if(c.error||i.error)throw c.error||i.error;setCategories(c.data||[]);setItems(i.data||[])}).catch(()=>setError('تعذر تحميل المكتبة الآن')).finally(()=>setLoading(false))},[]);
 return{categories,items,loading,error};
}

const Empty=({text})=><div className="library-empty"><FiBookOpen/><h2>{text}</h2><p>سيتم إضافة المحتوى من لوحة الإدارة قريبًا.</p></div>;

export function LibraryPage(){const{categories,items,loading,error}=useLibrary(),[q,setQ]=useState('');const shown=useMemo(()=>categories.filter(c=>`${c.name} ${c.description||''}`.toLowerCase().includes(q.toLowerCase())),[categories,q]);return <main className="library-page page"><section className="library-hero"><div><span>مكتبة محمد الحاوي</span><h1>ملفات ومصادر<br/><em>جاهزة للتحميل</em></h1><p>مكتبة منظمة إلى أقسام، تضم ملفات وأدلة وقوالب وروابط مفيدة مع وصف واضح لكل محتوى.</p><div className="library-search"><FiSearch/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث داخل الأقسام..."/></div></div><div className="library-hero-card"><FiBookOpen/><b>{categories.length}</b><span>قسم متاح</span><small>{items.length} ملف ومصدر</small></div></section>{loading?<div className="catalog-loading"><FiLoader/> جارٍ تحميل المكتبة</div>:error&&!categories.length?<Empty text={error}/>:shown.length?<section className="library-section"><header><span>الأقسام</span><h2>اختر القسم المناسب</h2></header><div className="library-categories">{shown.map(c=><Link to={`/library/category/${c.slug}`} key={c.id}><div className="library-category-icon">{c.cover_url?<img src={c.cover_url} alt=""/>:<FiFolder/>}</div><div><small>{items.filter(x=>x.category_id===c.id).length} عنصر</small><h3>{c.name}</h3><p>{c.description||'استكشف الملفات والمصادر المتاحة داخل هذا القسم.'}</p><span>فتح القسم <FiArrowLeft/></span></div></Link>)}</div></section>:<Empty text="لا توجد أقسام بعد"/>}</main>}

export function LibraryCategory(){const{slug}=useParams(),{categories,items,loading}=useLibrary(),[q,setQ]=useState('');const category=categories.find(c=>c.slug===slug),shown=items.filter(x=>x.category_id===category?.id&&`${x.title} ${x.description||''}`.toLowerCase().includes(q.toLowerCase()));if(loading)return <main className="page"><div className="catalog-loading"><FiLoader/> جارٍ التحميل</div></main>;if(!category)return <Empty text="القسم غير موجود"/>;return <main className="library-page page"><Link className="article-back" to="/library"><FiArrowLeft/> العودة إلى المكتبة</Link><section className="library-category-head"><small>قسم المكتبة</small><h1>{category.name}</h1><p>{category.description}</p><div className="library-search compact"><FiSearch/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="ابحث داخل القسم..."/></div></section>{shown.length?<div className="library-items">{shown.map(item=><article key={item.id}>{item.cover_url?<img src={item.cover_url} alt={item.title}/>:<div className="library-file-placeholder"><FiFile/></div>}<div><small>{item.file_type||'ملف للتحميل'}</small><h2>{item.title}</h2><p>{item.summary||item.description}</p><span>{item.file_size||'رابط خارجي'}</span><Link to={`/library/item/${item.id}`}>عرض التفاصيل <FiArrowLeft/></Link></div></article>)}</div>:<Empty text="لا توجد عناصر في هذا القسم بعد"/>}</main>}

export function LibraryItem(){const{id}=useParams(),{categories,items,loading}=useLibrary(),item=items.find(x=>String(x.id)===id),category=categories.find(c=>c.id===item?.category_id);if(loading)return <main className="page"><div className="catalog-loading"><FiLoader/> جارٍ التحميل</div></main>;if(!item)return <Empty text="العنصر غير موجود"/>;return <main className="library-page page"><Link className="article-back" to={category?`/library/category/${category.slug}`:'/library'}><FiArrowLeft/> العودة إلى {category?.name||'المكتبة'}</Link><article className="library-detail"><div className="library-detail-cover">{item.cover_url?<img src={item.cover_url} alt={item.title}/>:<FiFile/>}</div><div className="library-detail-copy"><span>{category?.name} · {item.file_type||'ملف'}</span><h1>{item.title}</h1><p className="lead">{item.summary}</p><div className="library-info"><div><small>نوع المحتوى</small><b>{item.file_type||'رابط تحميل'}</b></div><div><small>الحجم</small><b>{item.file_size||'غير محدد'}</b></div></div><div className="library-description">{item.description?.split('\n').map((p,i)=><p key={i}>{p}</p>)}</div><a className="library-download" href={item.download_url} target="_blank" rel="noreferrer"><FiDownload/> تحميل أو فتح الملف <FiExternalLink/></a></div></article></main>}

