import {useEffect,useState} from'react';
import {FiCheckCircle,FiFolderPlus,FiLink,FiLoader,FiLock,FiLogOut,FiPlusCircle,FiTrash2} from'react-icons/fi';
import {adminEmailFromUsername,supabase,supabaseReady} from'./supabase.js';

const slugify=value=>value.trim().toLowerCase().replace(/[أإآ]/g,'ا').replace(/ة/g,'ه').replace(/[^\p{L}\p{N}]+/gu,'-').replace(/^-|-$/g,'');
const blankItem={category_id:'',title:'',summary:'',description:'',download_url:'',cover_url:'',file_type:'',file_size:'',published:true};

export function LibraryAdmin(){const[session,setSession]=useState(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(''),[categories,setCategories]=useState([]),[items,setItems]=useState([]),[login,setLogin]=useState({username:'',password:''}),[cat,setCat]=useState({name:'',description:'',cover_url:''}),[item,setItem]=useState(blankItem);
 const load=async()=>{const[c,i]=await Promise.all([supabase.from('library_categories').select('*').order('sort_order'),supabase.from('library_items').select('*').order('created_at',{ascending:false})]);setCategories(c.data||[]);setItems(i.data||[])};
 useEffect(()=>{if(!supabaseReady){setLoading(false);return}supabase.auth.getSession().then(({data})=>{setSession(data.session);if(data.session)load();setLoading(false)});const{sub}=supabase.auth.onAuthStateChange((_,s)=>setSession(s)).data.subscription;return()=>sub.unsubscribe()},[]);
 const signIn=async e=>{e.preventDefault();setLoading(true);setMessage('');const{error}=await supabase.auth.signInWithPassword({email:adminEmailFromUsername(login.username),password:login.password});if(error)setMessage('بيانات الدخول غير صحيحة');else await load();setLoading(false)};
 const addCategory=async e=>{e.preventDefault();setMessage('');const{error}=await supabase.from('library_categories').insert({...cat,slug:slugify(cat.name)});if(error)setMessage(error.message.includes('duplicate')?'اسم القسم موجود بالفعل':'تعذر إضافة القسم');else{setCat({name:'',description:'',cover_url:''});setMessage('تمت إضافة القسم بنجاح');load()}};
 const addItem=async e=>{e.preventDefault();setMessage('');const{error}=await supabase.from('library_items').insert(item);if(error)setMessage('تعذر إضافة العنصر، راجع البيانات');else{setItem(blankItem);setMessage('تمت إضافة الملف بنجاح');load()}};
 const remove=async(id,type)=>{if(!confirm('هل تريد الحذف نهائيًا؟'))return;await supabase.from(type==='category'?'library_categories':'library_items').delete().eq('id',id);load()};
 if(!supabaseReady)return <main className="admin-page page"><div className="admin-login"><FiLock/><h1>لوحة الإدارة قيد التفعيل</h1><p>يجب ربط Supabase أولًا لحماية بيانات الدخول وحفظ المكتبة.</p></div></main>;
 if(loading)return <main className="page"><div className="catalog-loading"><FiLoader/> جارٍ التحميل</div></main>;
 if(!session)return <main className="admin-page page"><form className="admin-login" onSubmit={signIn}><FiLock/><span>دخول خاص</span><h1>لوحة إدارة المكتبة</h1><p>أدخل بيانات الأدمن لإضافة الأقسام وروابط التحميل.</p><label>اسم المستخدم<input required value={login.username} onChange={e=>setLogin({...login,username:e.target.value})} inputMode="tel" autoComplete="username"/></label><label>كلمة المرور<input required type="password" value={login.password} onChange={e=>setLogin({...login,password:e.target.value})} autoComplete="current-password"/></label>{message&&<div className="admin-message">{message}</div>}<button><FiLock/> تسجيل الدخول</button></form></main>;
 return <main className="admin-page page"><header className="admin-head"><div><span>لوحة الإدارة</span><h1>إدارة مكتبة التحميلات</h1><p>أضف قسمًا أو ملفًا جديدًا باستخدام رابط التحميل فقط.</p></div><button onClick={()=>supabase.auth.signOut()}><FiLogOut/> تسجيل الخروج</button></header>{message&&<div className="admin-success"><FiCheckCircle/> {message}</div>}<div className="admin-forms"><form onSubmit={addCategory}><header><FiFolderPlus/><div><h2>إضافة قسم</h2><p>أنشئ قسمًا لتنظيم الملفات.</p></div></header><label>اسم القسم<input required value={cat.name} onChange={e=>setCat({...cat,name:e.target.value})}/></label><label>وصف القسم<textarea required value={cat.description} onChange={e=>setCat({...cat,description:e.target.value})}/></label><label>رابط صورة الغلاف — اختياري<input type="url" value={cat.cover_url} onChange={e=>setCat({...cat,cover_url:e.target.value})}/></label><button><FiPlusCircle/> إضافة القسم</button></form><form onSubmit={addItem}><header><FiLink/><div><h2>إضافة ملف أو مصدر</h2><p>أدخل بيانات العنصر ورابط التحميل.</p></div></header><label>القسم<select required value={item.category_id} onChange={e=>setItem({...item,category_id:e.target.value})}><option value="">اختر القسم</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>العنوان<input required value={item.title} onChange={e=>setItem({...item,title:e.target.value})}/></label><label>وصف مختصر<input required value={item.summary} onChange={e=>setItem({...item,summary:e.target.value})}/></label><label>التفاصيل<textarea required value={item.description} onChange={e=>setItem({...item,description:e.target.value})}/></label><label>رابط التحميل<input required type="url" value={item.download_url} onChange={e=>setItem({...item,download_url:e.target.value})}/></label><div className="admin-form-row"><label>نوع الملف<input placeholder="PDF أو ZIP" value={item.file_type} onChange={e=>setItem({...item,file_type:e.target.value})}/></label><label>الحجم<input placeholder="مثال: 12 MB" value={item.file_size} onChange={e=>setItem({...item,file_size:e.target.value})}/></label></div><label>رابط صورة الغلاف — اختياري<input type="url" value={item.cover_url} onChange={e=>setItem({...item,cover_url:e.target.value})}/></label><button><FiPlusCircle/> نشر في المكتبة</button></form></div><section className="admin-list"><h2>المحتوى الحالي</h2><div>{categories.map(c=><article key={c.id}><div><b>{c.name}</b><span>{items.filter(x=>x.category_id===c.id).length} عنصر</span></div><button onClick={()=>remove(c.id,'category')}><FiTrash2/></button></article>)}</div></section></main>}

